export * from "../vistaEfermero/vistaCitas";
export * from "../vistaEfermero/vistaPacientes";
export * from "../vistaEfermero/vistaHistoriaMedica";
export * from "./vistaMedicos";
export * from "./vistaMedicamentos";
export * from "./vistaAnalisis";
export * from "./VistaDetalleMedico";
export * from "./vistaProgramacionMedico";
export * from "../vistaEfermero/vistaHorarioMedicos";
export * from "./VistaHorarioMedicosAdministrador";
export * from "../vistaEfermero/vistaListaCitas";
export * from  "./vistaAtencionMedica";
export * from "./vistaRecetaAtencion"
export * from "./VistaAnalisisAtencion";